export const mbdtf = [
  {
    src: "./src/assets/audio/Dark Fantasy.mp3",
    songName: "Dark Fantasy",
    songLength: "4:41",
    artists: "Kanye West",
  },
  {
    src: "./src/assets/audio/Gorgeous.mp3",
    songName: "Gorgeous",
    songLength: "5:58",
    artists: "Kanye West & Kid Cudi & Raekwon",
  },
  {
    src: "./src/assets/audio/POWER.mp3",
    songName: "POWER",
    songLength: "4:53",
    artists: "Kanye West",
  },
  {
    src: "./src/assets/audio/All of the Lights (Interlude).mp3",
    songName: "All of the Lights (Interlude)",
    songLength: "1:03",
    artists: "Kanye West",
  },
  {
    src: "./src/assets/audio/All of the Lights.mp3",
    songName: "All of the Lights",
    songLength: "5:00",
    artists: "Kanye West & Rihanna",
  },
  {
    src: "./src/assets/audio/Monster.mp3",
    songName: "Monster",
    songLength: "6:19",
    artists: "Kanye West & Bon Iver & JAY-Z & Nicki Minaj & Rick Ross",
  },
  {
    src: "./src/assets/audio/So Appalled.mp3",
    songName: "So Appalled",
    songLength: "6:38",
    artists: "Kanye West & CyHi & JAY-Z & Pusha T & RZA & Swizz Beatz",
  },
  {
    src: "./src/assets/audio/Devil In a New Dress.mp3",
    songName: "Devil In a New Dress",
    songLength: "5:52",
    artists: "Kanye West & Rick Ross",
  },
  {
    src: "./src/assets/audio/Runaway.mp3",
    songName: "Runaway",
    songLength: "9:08",
    artists: "Kanye West & Pusha T",
  },
  {
    src: "./src/assets/audio/Hell of a Life.mp3",
    songName: "Hell of a Life",
    songLength: "5:28",
    artists: "Kanye West",
  },
  {
    src: "./src/assets/audio/Blame Game.mp3",
    songName: "Blame Game",
    songLength: "7:50",
    artists: "Kanye West & John Legend",
  },
  {
    src: "./src/assets/audio/Lost In the World.mp3",
    songName: "Lost In the World",
    songLength: "4:17",
    artists: "Kanye West & Bon Iver",
  },
  {
    src: "./src/assets/audio/Who Will Surviv In America.mp3",
    songName: "Who Will Surviv In America",
    songLength: "1:39",
    artists: "Kanye West",
  },
  {
    src: "./src/assets/audio/See Me Now.mp3",
    songName: "See Me Now",
    songLength: "6:04",
    artists: "Kanye West & Beyoncé & Big Sean & Charlie Wilson",
  },
];
